config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  
  get     '/help',    to: 'static_pages#help'
  get     '/about',   to: 'static_pages#about'
  get     '/contact', to: 'static_pages#contact'
  get     '/signup',  to: 'users#new'
  get     '/login',   to: 'sessions#new'
  post    '/login',   to: 'sessions#create'
  delete  '/logout',  to: 'sessions#destroy'
  resources :users do    
    member do
      get :following, :followers
    end
  end
  #For Resources I need to look onto the RESTfull Routes Table to see all generated routes!
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  before_action :get_user, only: [:edit, :update]
  before_action :valid_user, only: [:edit, :update]
  before_action :check_expiration, only: [:edit, :update]
  
  def new
  end

  def create
    @user = User.find_by(email: params[:password_reset][:email].downcase)
    if @user
      @user.create_reset_digest
      @user.send_password_reset_email
      flash[:info] = "Email send with password reset instructions"
      redirect_to root_url
    else
      flash.now[:danger] = "Email address not found"
      render "new"  # equivalent to: render :action => new
    end
  end

  def edit # changing of password. Email should link to this action
  end
  
  def update
    if params[:user][:password].empty?
      @user.errors.add(:password, "can't be empty, dummy!")
      render 'edit'
    elsif @user.update(user_params) # if changing password successful
      @user.forget
      reset_session
      log_in @user
      @user.update_attribute(:reset_digest, nil) 
      flash[:sucess] = "Your password has been changed successfully"
      redirect_to @user
    else
      render 'edit'
    end
    
  end
  
  
  private
  
    def user_params 
      params.require(:user).permit(:password, :password_confirmation)
    end
  
    def get_user
      @user = User.find_by(email: params[:email])
    end
    
    def valid_user
      unless (@user&.validate_reset(params[:id]))
        redirect_to root_url
      end
    end
    
    def check_expiration
      if @user.password_reset_expired?
        flash[:danger] = "Your password reset has unfortunately expired. Idiot!"
        redirect_to new_password_reset_url
      end
    end
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/views/password_resets/edit.html.erb
<% provide(:title, "Reset password") %> 
<h1>Reset password</h1>
<div class="row"> 
  <div class="col-md-6 col-md-offset-3"> 
  <p><b>Change password for email-adress: <%= @user.email %>: </b></p>
  <!--after we submit the form the value of email will be lost. :( -->
  
  <!-- The model is needed here because we are changing the password for a specific user in the database-->
    <%= form_with(model: @user, url: password_reset_path(params[:id]), local: true) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      
      <%= hidden_field_tag :email, @user.email %>
      
      <%= f.label :password %> 
      <%= f.password_field :password, class: 'form-control' %>
      
      <%= f.label :password_confirmation %> 
      <%= f.password_field :password_confirmation, class: 'form-control' %>
      
      <%= f.submit "Change my password", class: "btn btn-primary" %> 
    <% end %>
  </div> 
</div>

app/views/password_resets/new.html.erb
<% provide(:title, "Password Reset") %> 
<h1>Password Reset</h1>
<div class="row"> 
  <div class="col-md-6 col-md-offset-3"> 
  <!--using :password_reset because @password_reset doesn't correspond to an Active Record object, form_for won't automatically create a URL for it.-->
    <!--https://apidock.com/rails/ActionView/Helpers/FormHelper/form_with-->
    <!--Adding a scope prefixes the input field names (necessary if no model) The parameters in the forms are accessible 
    in controllers according to their name nesting. So inputs named title and post[title] are accessible as params[:title] and params[:post][:title] respectively.-->
    <%= form_with(url: password_resets_path, scope: :password_reset, local: true) do |f| %> 
      
      <%= f.label :email %> 
      <%= f.email_field :email, class: 'form-control' %> 
      
      <%= f.submit "Submit", class: "btn btn-primary" %> 
    <% end %>
  </div> 
</div>